export { Hero } from './Hero';
export { Brand } from './Brand';
export { Features } from './Features';
export { Services } from './Services';
export { Products } from './Products';
export { Process } from './Process';
export { ContactCTA } from './ContactCTA';
export { Footer } from './Footer';
export { WhatsAppButton } from './WhatsAppButton';
export type { ConfigClinica } from './types';
